### ISSUE TITLE
What is the distinction between these two observations?

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/datasets#16]
While taking a look over the ESIF dataset i noticed this fact:

```
<http://data.openbudgets.eu/resource/dataset/ESIF-2014-2020/observation/2> a qb:Observation ;
    obeu-dimension:administrativeClassification <http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/MS/AT> ;
    esif-measure:amountEU 3.73093691E6 ;
    esif-measure:amountNational 3.61895731E6 ;
    esif-measure:amountTotal 7.34989422E6 ;
    obeu-dimension:functionalClassification <http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/function/1> ;
    obeu-dimension:fund eu-funds:eafrd ;
    qb:dataSet <http://data.openbudgets.eu/resource/dataset/ESIF-2014-2020> .

<http://data.openbudgets.eu/resource/dataset/ESIF-2014-2020/observation/3> a qb:Observation ;
    obeu-dimension:administrativeClassification <http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/MS/AT> ;
    esif-measure:amountEU 3.197946E5 ;
    esif-measure:amountNational 3.1019635E5 ;
    esif-measure:amountTotal 6.2999095E5 ;
    obeu-dimension:functionalClassification <http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/function/1> ;
    obeu-dimension:fund eu-funds:eafrd ;
    qb:dataSet <http://data.openbudgets.eu/resource/dataset/ESIF-2014-2020> .
```

My question is what is the distinction between these two observations? It seems like all dimensions are the same except the measure. That is an integrity constraint violation of the Data Cube Vocabulary as described in it's [desscription](https://www.w3.org/TR/vocab-data-cube/) IC-12, and considered as duplicate observation. It seems that, this is the case with most if not all the ESIF dataset observations.

**Comment by fathoni** [comment]
Hi Sotiris, thanks for bringing this up! From the raw dataset here https://cohesiondata.ec.europa.eu/dataset/ESIF-FINANCE-DETAILS/e4v6-qrrq there are still more columns to be mapped as dimensions. We are currently trying to be in contact with the the publisher of this dataset. A few weeks ago a representative from the EU stated via email that additional metadata for this dataset will be published.   Once it is published, we are going to update the transformation result and fix this issue.

**Comment by jindrichmynarz** [comment]
You can use various Data Cube Vocabulary validators, such as [NoSPA-RDF-Data-Cube-Validator](https://github.com/yyz1989/NoSPA-RDF-Data-Cube-Validator), to validate integrity constraints defined for this vocabulary. All OpenBudgets.eu must satisfy the integrity constraints.

[IC-12](https://www.w3.org/TR/vocab-data-cube/#ic-12) is violated by other datasets too:
- [budget-athens-expenditure-2004.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2004.ttl)
- [budget-athens-expenditure-2005.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2005.ttl)
- [budget-athens-expenditure-2006.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2006.ttl)
- [budget-athens-expenditure-2007.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2007.ttl)
- [budget-athens-expenditure-2008.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2008.ttl)
- [budget-athens-expenditure-2009.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2009.ttl)
- [budget-athens-expenditure-2010.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2010.ttl)
- [budget-athens-expenditure-2011.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2011.ttl)
- [budget-athens-expenditure-2012.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2012.ttl)
- [budget-athens-expenditure-2013.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2013.ttl)
- [budget-athens-expenditure-2014.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2014.ttl)
- [budget-athens-expenditure-2015.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-athens/dataset/budget-athens-expenditure-2015.ttl)
- [budget-thessaloniki-expenditure-2011.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2011.ttl)
- [budget-thessaloniki-expenditure-2012.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2012.ttl)
- [budget-thessaloniki-expenditure-2013.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2013.ttl)
- [budget-thessaloniki-expenditure-2014.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2014.ttl)
- [budget-thessaloniki-expenditure-2015.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2015.ttl)

**Comment by skarampatakis** [comment]
@jindrichmynarz Did you ckecked with the DSD attached? These datasets does not contain DSDs but are on seperate file under folder DSD.

**Comment by jindrichmynarz** [comment]
Right, it seems that the NoSPA-RDF-Data-Cube-Validator does a poor job when DSD is not present. With the DSD mixed in, the datasets pass the IC-12. Instead, they trigger IC-11 violations.

**Comment by skarampatakis** [comment]
We are aware of this problem. It will be fixed at the next version of the datasets on the pipelines we develop for LinkedPipes.

**Comment by fathoni** [comment]
In the end, the best way to deal with incomplete codelists are doing aggregation. As we know we could not manage to encode all of EU's codelists provided in this datasets, since some of them are using national-defined code which is not decode-able.

**Comment by jindrichmynarz** [comment]
I think the best way to deal with incomplete code lists is to use concept placeholders. Why aggregation? That would incur unnecessary data loss.

**Comment by skarampatakis** [comment]
I am with Jindřich on this.
I believe that all of our transformations have to be 1:1 so we can get the
original version of our data by reversing the transformations.

Στις 23 Νοε 2016 16:46, ο χρήστης "Jindřich Mynarz" <
notifications@github.com> έγραψε:

**Comment by fathoni** [comment]
> I believe that all of our transformations have to be 1:1 so we can get the
> original version of our data by reversing the transformations.

Well, seems that more things need to be done on the codelist in this case (e.g., adding a placeholder for non-identified codelist). Reopening the issue.

**Comment by fathoni** [comment]
Placeholder added for national priority code list. DSD was also modified due to this change. Previous priority code list was renamed to EAFRD-priority.
