### ISSUE TITLE
Missing DSD for the budget of Athens

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#2]
The data structure definition for the budget of Athens is missing. Please add it.

**Comment by skarampatakis** [comment]
DSDs for all greek Municipalities changed to one unique as it is about the same structure for every dataset.

**Comment by jindrichmynarz** [comment]
Is the common DSD a part of this repository? I cannot find it.

**Comment by skarampatakis** [comment]
you can find it here [datasets/greek-municipalities/dsd/dsd.ttl](url)
