### ISSUE TITLE
Duplicate value. False positive?

### ISSUE THREAD

**Issue by fathoni** [openbudgets/datasets#20]
Hi @jindrichmynarz , I played with around with the [RDF Data Cube validator tool](https://github.com/yyz1989/NoSPA-RDF-Data-Cube-Validator) you've suggested on the transformed [Aragon 2013 Expenditure Data](https://github.com/openbudgets/datasets/blob/master/Aragon/2013/dataset/aragon-2013-expenditure.ttl). The validator duplicate observations, for example: 

> The following observations has duplicated values: 
>     http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/329
>     http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/4786
> ...

The content of the observation 329, is:

```
<http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/329> a qb:Observation ;
    aragon-dimension:administrativeClassification <http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2013/10010> ;
    aragon-dimension:functionalClassification <http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2013/1211> ;
    aragon-dimension:economicClassification <http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2013/120006> ;
    aragon-dimension:fundingClassification <http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2013/91002> ;
    obeu-measure:amount "204.123,16"^^xsd:double ;
    qb:dataSet <http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure> .
```

However when I load the aragon 2013 expenditure ttl dataset on local Fuseki installation, I found no duplicates.

```
PREFIX aragon-dimension: <http://data.openbudgets.eu/ontology/dsd/aragon-budget/dimension/> 
SELECT ?subject ?predicate ?object
WHERE {
  ?subject aragon-dimension:administrativeClassification <http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2013/10010> .
    ?subject aragon-dimension:functionalClassification <http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2013/1211> .
    ?subject aragon-dimension:economicClassification <http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2013/120006> .
    ?subject aragon-dimension:fundingClassification <http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2013/91002> 
}
```

And the only result is:

> http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/329

I inspected the raw dataset and found no duplicated row as well, according to IC-12 in https://www.w3.org/TR/vocab-data-cube/ . Is it a false positive or there is something I can do to fix this?

Also, I found:

> ## Integrity Constraint 4: Dimensions Have Range
> 
> The following dimensions do not have a declared rdfs:range: 
>     http://data.openbudgets.eu/ontology/dsd/dimension/operationCharacter
>     http://data.openbudgets.eu/ontology/dsd/dimension/fiscalYear
>     http://data.openbudgets.eu/ontology/dsd/dimension/budgetaryUnit
>     http://data.openbudgets.eu/ontology/dsd/dimension/budgetPhase

How can we provide OBEU's DSD during validation?

**Comment by jindrichmynarz** [comment]
I checked the Aragon 2013 expenditure dataset and it seems that the NoSPA DCV Validator is confused by the other errors the data has. For example, there are empty observations without any dimensions, such as `<http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/5188>` and `<http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure/observation/5189>`. I would fix this and other issues reported by the NoSPA DCV Validator first before considering duplicity of observations again. 

Originally, I thought that the NoSPA DCV Validator does a poor job when the DSD of the validated dataset is unavailable. However, in this case even with the DSD mixed in, it still reports errors violating IC-12.

I checked for duplicate observations using the following query and obtained empty results.

``` sparql
PREFIX aragon-dimension:  <http://data.openbudgets.eu/ontology/dsd/aragon-budget/dimension/>
PREFIX obeu-dimension:    <http://data.openbudgets.eu/ontology/dsd/dimension/>
PREFIX qb:                <http://purl.org/linked-data/cube#>

SELECT (GROUP_CONCAT(STR(?observation); separator = ", ") AS ?duplicateObservations)
WHERE {
  ?observation a qb:Observation ;
    qb:dataSet/obeu-dimension:budgetaryUnit ?budgetaryUnit ;
    qb:dataSet/obeu-dimension:budgetPhase ?budgetPhase ;
    qb:dataSet/obeu-dimension:operationCharacter ?operationCharacter ;
    qb:dataSet/obeu-dimension:fiscalYear ?fiscalYear ;
    aragon-dimension:administrativeClassification ?administrativeClassification ;
    aragon-dimension:functionalClassification ?functionalClassification ;
    aragon-dimension:economicClassification ?economicClassification ;
    aragon-dimension:fundingClassification ?fundingClassification .
}
GROUP BY ?budgetaryUnit ?budgetPhase ?operationCharacter ?fiscalYear
         ?administrativeClassification ?functionalClassification
         ?economicClassification ?fundingClassification
HAVING (COUNT(DISTINCT ?observation) > 1)
```

That would imply there are no duplicate observations.

Anyway, I'd fix the other errors and then re-check IC-12.

**Comment by jindrichmynarz** [comment]
Regarding your other question about providing the OpenBudgets.eu data model, you can mix it in with the validated dataset using several methods. If you have your dataset and the OBEU data model in Turtle or N-Triples, you can simply concatenate the files (e.g., `cat dataset.ttl budget-components.ttl ... > complete_dataset.ttl`). If you are validating this using LinkedPipes or UnifiedViews, you can have more inbound edges to the SPARQL DPU that does the validation. We are considering building a LinkedPipes pipeline fragment that would perform the DCV validation and automatically mix in the required data about the OpenBudgets.eu data model.

**Comment by fathoni** [comment]
Hi Jindrich, I have just fixed this in the Aragon 2013 Expenditure dataset (https://github.com/openbudgets/datasets/blob/master/Aragon/2013/dataset/aragon-2013-expenditure.ttl). Can you provide a feedback before I apply the new fixes in the pipeline to the whole aragon dataset? In particular, it still has an issue with duplicates when I run the validator with nospa option,

`java -jar nospa-rdf-data-cube-validator-0.9.9-jar-with-dependencies.jar aragon-2013-expenditure.ttl nospa`

but the issue does not persist when I use sparql option instead of nospa. Another thing is that it breaks the IC-5 constraint:

> ## Integrity Constraint 5: Concept Dimensions Have Code Lists
> 
> The following concept dimensions do not have a code list: 
>     http://data.openbudgets.eu/ontology/dsd/dimension/functionalClassification
>     http://data.openbudgets.eu/ontology/dsd/dimension/economicClassification
>     http://data.openbudgets.eu/ontology/dsd/dimension/classification
>     http://data.openbudgets.eu/ontology/dsd/dimension/programmeClassification
>     http://data.openbudgets.eu/ontology/dsd/dimension/administrativeClassification

Do you have any pointer regarding from where  I can fetch the correct code list for those classifications? Those classifications are used in the dataset under the aragon-dimension DSD, but not from obeu-dimension DSD.

**Comment by jindrichmynarz** [comment]
Regarding the violations of [IC-5](https://www.w3.org/TR/vocab-data-cube/#ic-5), these properties are defined by the OpenBudgets.eu data model as abstract. They should not be directly used. Instead, their subproperties should be defined. This is why they don't have any specific code list defined via `qb:codeList`. However, I see that in this dataset you already use their subproperties. This error is only reported because you mix the OpenBudgets.eu data model into the dataset. 

@jakubklimek, do you have an opinion on satisfying IC-5 for abstract properties? Should we provide them with "place-holder" code lists?

Regarding the duplicate observations violating [IC-12](https://www.w3.org/TR/vocab-data-cube/#ic-12), I think there may be a problem with your dataset not conforming to your DSD. The DSD defines `obeu-dimension:budgetPhase` as a dimension attached to `qb:DataSet`, yet it is missing from `<http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure>`.

I also noticed you instantiate properties, which is not possible in the RDF Schema semantics (only classes can be instantiated). For example, you have `aragon-dimension:economicClassification a obeu-dimension:economicClassification`. Instead, just use `aragon-dimension:economicClassification rdfs:subPropertyOf obeu-dimension:economicClassification` (the `aragon-dimension:economicClassification rdfs:subPropertyOf obeu-dimension:classification` is inferred transitively).

Also note that many of your measures don't conform to their data type. For example, `8.500,00` is not valid `xsd:double`.

**Comment by jakubklimek** [comment]
@jindrichmynarz Since they are abstract = not to be actually used in instances of qb:Observations or DSDs, I would leave it as it is. For validation purposes, we could separate the abstract ComponentProperties so that the OBEU data model can be mixed with DSDs without the need to delete them manually.

**Comment by jindrichmynarz** [comment]
OK, I've added a SPARQL Update that removes abstract properties from the OBEU data model into the validation pipeline fragment.

**Comment by fathoni** [comment]
> This error is only reported because you mix the OpenBudgets.eu data model into the dataset. 

I haven't fully understood the statement. I merged the dataset, aragon DSD and OBEU component DSD  in UnifiedViews and the result will mix the DSDs and overall dataset. I thought it was the correct way to do this as it is AFAIK similar to the cat command you've suggested. Or am I mistaken?

The Aragon DSD has been fixed without non-class instantiation. As for IC-12, I've tried removing the  budgetPhase attachment from the DSD, but the issue persists, unless I am suing sparql validator.

Regarding the valid double format, is there any particular way to convert String-typed representation of measure into double in UnifiedViews? Or should this be done outside UV, e.g. spreadsheets programs?

**Comment by skarampatakis** [comment]
Are budget values of type Double or Decimal?

**Comment by fathoni** [comment]
You're right, according to D 1.2 , section 4.2.1 it should be Decimal.

**Comment by jindrichmynarz** [comment]
> I haven't fully understood the statement. I merged the dataset, aragon DSD and OBEU component DSD in UnifiedViews and the result will mix the DSDs and overall dataset. I thought it was the correct way to do this as it is AFAIK similar to the cat command you've suggested. Or am I mistaken?

You're right. I only made that statement to explain why is the error detected.

> The Aragon DSD has been fixed without non-class instantiation. As for IC-12, I've tried removing the budgetPhase attachment from the DSD, but the issue persists, unless I am suing sparql validator.

So `obeu-dimension:budgetPhase` shouldn't be in the dataset?

> Regarding the valid double format, is there any particular way to convert String-typed representation of measure into double in UnifiedViews? Or should this be done outside UV, e.g. spreadsheets programs?

Use SPARQL Update. For example, `BIND (xsd:decimal(REPLACE(REPLACE(?numberLike, "\\.", ""), ",", ".")) AS ?number)`.

> Are budget values of type Double or Decimal?

@skarampatakis, `xsd:decimal` is preferred.

**Comment by fathoni** [comment]
> So `obeu-dimension:budgetPhase` shouldn't be in the dataset?

AFAIK There is no official remarks about the Draft/Revised/Approved/Executed in  the [website](http://opendata.aragon.es/catalogo/presupuesto-gobierno-aragon-2013). Hence I am not including the budgetPhase for now, though I am inclined to digest that the budgetPhase for the dataset is Executed based on the year.

**Comment by jindrichmynarz** [comment]
OK. It seems to me then there are no duplicate observations in this dataset. It appears there is a bug in the NoSPA implementation of IC-12 in [yyz1989/NoSPA-RDF-Data-Cube-Validator](https://github.com/yyz1989/NoSPA-RDF-Data-Cube-Validator), especially since the SPARQL option finds no duplicates. I suggest you raise this as an issue of the validator.

**Comment by fathoni** [comment]
Alright then, I  have pushed the revision for [Aragon 13 expenditure](https://github.com/openbudgets/datasets/blob/master/Aragon/2013/dataset/aragon-2013-expenditure.ttl) based on your suggestions. Let me know if you have some further comments. As for the bug, I will submit this to the NoSPA repo. Thanks!

**Comment by jindrichmynarz** [comment]
I think the problem of the Aragon dataset is invalid `qb:structure` link from the dataset to its DSD:

```
<http://data.openbudgets.eu/resource/dataset/aragon-2013-expenditure> qb:structure <http://example.openbudgets.eu/ontology/dsd/aragon-budget> .
```

However, the DSD's IRI is `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp>`.

When you fix this issue, then NoSPA-RDF-Data-Cube-Validator returns no violations of IC-12 for this dataset.

**Comment by fathoni** [comment]
Indeed, ah this is the problem when I created several version of DSDs that I did not manage to track all of them. Tested using nospa option and solved now. Thanks.
