### ISSUE TITLE
0.0 amounts in Greek datasets

### ISSUE THREAD

**Issue by ChristianeEngels** [openbudgets/datasets#23]
While preparing the data for analysis, I noticed that there are many observations in the Greek data sets with amount = 0.0, e.g. 12.000 out of 30.000 observations for Thessaloniki.

Is this perhaps due to an error or missing data?

https://github.com/openbudgets/datasets/tree/master/greek-municipalities

**Comment by skarampatakis** [comment]
This comes from the actual data. In some cases there is a drafted amount but 0 in reserved or executed meaning that this expenditure never happened. If the values are missing this is noted by for example 
`athens-be2004-observation:14 <http://purl.org/linked-data/sdmx/2009/attribute#obsStatus> sdmx-code:obsStatus-M .`

as idented to be by OpenBudgets.eu Data Model.
