### ISSUE TITLE
Provide code lists for dimensions

### ISSUE THREAD

**Issue by larjohn** [openbudgets/datasets#25]
Please make sure you have provided the code lists for every coded dimension in your datasets, in the code-lists repository.

Even if there are no actual data about the code list terms, a SKOS representation with an id as both prefLabel and notation is very helpful when it comes to presentation for the end users.

**Comment by jindrichmynarz** [comment]
Can you point out specific datasets that are missing code lists?

Regarding the repository where code lists can be shared, do you prefer [openbudgets/code-lists](https://github.com/openbudgets/code-lists) to providing them alongside the datasets, as in [here](https://github.com/openbudgets/datasets/tree/master/greek-municipalities/codelist)?

**Comment by larjohn** [comment]
Example:

http://linked.opendata.cz/resource/domain/mfcr/monitor/ciselniky/Nastroj/36

in the Decin dataset. I grep-ed my repos folder and couldn't find either the term, or a namespace part.

**Comment by jindrichmynarz** [comment]
This is a reused code lists that we have not created in the OpenBudgets.eu. It is dereferenceable, dumps of the code lists are [here](http://linked.opendata.cz/dataset/mfcr-ciselniky).

However, it raises another question related to caching and synchronization of linked data. This is probably a question for the OpenBudgets.eu platform. When we need to fetch linked data, it should be preferably done once, or periodically if the data changes.

**Comment by larjohn** [comment]
A dereferenceable code list was a fortunate surprise here :) 

I don't think it's a good idea to depend on a remote server, anyways. So I will cache the code lists together with the datasets, for the time being.

**Comment by jindrichmynarz** [comment]
Do you expect to find copies of the linked code lists in this repository or [openbudgets/code-lists](https://github.com/openbudgets/code-lists)? Or you expect to resolve caching as part of the OpenBudgets.eu infrastructure?

**Comment by larjohn** [comment]
The requirement here is to be able to find the codelist in the same endpoint with the datasets, so that I can get the implicit attributes (like prefLabel and notation). I would like to be able to download the datasets and don't have to guess where the code lists reside. This is crucial in order to have the user interface friendliness required.

I don't really understand what you mean by "resolve caching".

**Comment by jindrichmynarz** [comment]
I see your point. My question is if you expect the copies of reused code lists to be made manually or automatically by the OpenBudgets.eu platform? If it is the first, then each ETL'd dataset in this repository can be accompanied by copies of code lists it reuses. If it is the latter, then the OpenBudgets.eu platform can run an automated task that periodically fetches any IRIs not described in its RDF store. For example, it can run a query like:

```
SELECT DISTINCT ?s
WHERE {
   [] ?p1 ?s .
   FILTER NOT EXISTS {
     ?s ?p2 [] .
   }
}
```

Consequently, something like [LDSpider](https://github.com/ldspider/ldspider) can be run with the list of retrieved IRIs.

The downside of the automated approach is that it relies on dereferenceability of code list IRIs that is often not possible. Hence, we may need to do some of the local caching manually.

**Comment by larjohn** [comment]
I understand what you were talking about, now. 

First of all, do we still commit to an end-to-end solution? From CSV to visualization? Because I feel I have missed some of the intermediate steps. If yes, then an automated solution would be preferred, but, also, manual importing of data is also desired. 

This is not only for code lists, but even for other data like country populations, polygons, election dates etc, in order to present them together with the budget data. Here in Greece, it is a common strategy to increase budgeted amounts one year before the regional elections, in order to acquire as many voters as possible. Such data in OpenSpending are now provided by the [Cosmopolitan API](http://cosmopolitan.openspending.org/), but we could be API-compatible, fetching data from DBpedia or so.

**Comment by skarampatakis** [comment]
@larjohn  Is this still an issue?
