### ISSUE TITLE
Incorrect IRIs for project partners

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#26]
If you check the IRIs of project partners in the [Czech ESF recipients dataset](https://github.com/openbudgets/datasets/tree/master/ESF-recipients-czech/2007-2013/datasets), then you will find IRIs like this one:

```
<http://data.openbudgets.eu/resource/dataset/list-of-beneficiaries-eu-funds/cz/2007-2013/partner/261238>
```

When you try to look it up in the [partner code list](https://github.com/openbudgets/datasets/blob/master/ESF-recipients-czech/2007-2013/codelists/eusf-czech-2007-2013-codelist-partners.ttl), you will fail. However, you will find the IRIs like this one:

```
<http://data.openbudgets.eu/resource/list-of-beneficiaries-eu-funds/cz/2007-2013/partner/261238>
```

Notice there is an extra `dataset` in the first IRI, which should probably be removed.

**Comment by jakubklimek** [comment]
Actually, It should be added where it is missing to adhere to the hierarchical IRI

**Comment by jindrichmynarz** [comment]
OK, then just the IRIs in the partner code list need to add `/dataset` part.
