### ISSUE TITLE
Invalid xsd:decimals in Czech ESF recipients dataset

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#29]
[Czech ESF recipients dataset](https://github.com/openbudgets/datasets/tree/master/ESF-recipients-czech/2007-2013/datasets) contains invalid amount data typed as `xsd:decimal`, e.g., `1.50777416E7`, `2.913992845E7`, or `4.857586908E7`.

**Comment by jakubklimek** [comment]
This seems to be a bug in t-excelToCsv, https://github.com/linkedpipes/etl/issues/159
