### ISSUE TITLE
Empty code list for the budget of Thessaloniki from 2011

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#3]
The code list for the [budget of Thessaloniki from 2011](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/codelist/budget-thessaloniki-expenditure-codelist-2011.ttl) is empty (contains only namespace prefixes).

**Comment by skarampatakis** [comment]
Codelist and dataset corrected. A typo in pipeline failed the conversion.
