### ISSUE TITLE
gr-dimension:budgetPhase is missing rdfs:range

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#35]
`<http://data.openbudgets.eu/ontology/dsd/greek-municipalities/dimension/budgetPhase>` in [Athens budgets' DSD](https://github.com/openbudgets/datasets/tree/master/greek-municipalities/municipality-of-athens/dsd) is missing `rdfs:range`, which is required for dimensions by the Data Cube Vocabulary (see [IC-4](https://www.w3.org/TR/vocab-data-cube/#ic-4)).

**Comment by skarampatakis** [comment]
Actually `gr-dimension:budgetPhase` is defined [here](datasets/greek-municipalities/codelist/budget-phase.ttl), where the range is defined. Please check if everything is ok.

**Comment by jindrichmynarz** [comment]
You're right. So this is rather a code organization issue.
