### ISSUE TITLE
"Dated" code lists in the Aragon dataset

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#36]
The [Aragon dataset](https://github.com/openbudgets/datasets/tree/master/Aragon) references "dated" code lists, such as `<http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2006>`. I wasn't able to find these code lists. Are they available?

The [code lists](https://github.com/openbudgets/Code-lists/tree/master/UnifiedViews/skosified) repository only contain these code lists for 2013 (e.g., `estructura_funcional_aragon_2013`).

**Comment by fathoni** [comment]
Hi Jindrich, the codelist for the aragon dataset is currrently available only for year 2013. I will provide the rest of the codelist once I have successfully converted the UV 2.3 pipeline into LinkedPipes, hopefully it can be finished next week.

**Comment by fathoni** [comment]
Completed, thanks.
