### ISSUE TITLE
ESIF funds code list missing a dot in prefix declaration

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#37]
The ESIF funds code list is missing a dot in a [namespace prefix declaration](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/codelists/esif-funds.ttl#L26) and hence cannot be parsed as valid RDF/Turtle.

**Comment by fathoni** [comment]
Thanks, will soon fix this once I have connection to my development machine (tonight/tomorrow).
