### ISSUE TITLE
Why is the ESIF program code list there if the ESIF dataset doesn't use it?

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#39]
The [ESIF program code list](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/codelists/esif-program.ttl) is not used in the [ESIF](https://github.com/openbudgets/datasets/tree/master/ESIF/2014/dataset) dataset. Why it was transformed to RDF?

**Comment by fathoni** [comment]
The program code list will be included in the dataset once the the other codelist (e.g. Priority, EAFRD_FA, EAFRD_MEASURE..) acquisition is completed.  This is correlated with the issue opened [here](https://github.com/openbudgets/datasets/issues/16).
