### ISSUE TITLE
Use a custom namespace for obeu-dimension:financialClassification

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#4]
The expenditure of Athens uses the property `obeu-dimension:financialClassification`. The property uses the namespace of the core data model of OpenBudgets.eu (`http://data.openbudgets.eu/ontology/dsd/dimension/`), but it is not defined as a part of the core. Please use a custom namespace for properties that extend the core data model.

**Comment by skarampatakis** [comment]
`obeu-dimension:financialClassifiation` changed to `obeu-dimension:functionalClassification` as it was supposed to be. Changed for all datasets.

**Comment by jindrichmynarz** [comment]
Right, but you define a specific code list for the functional classification? If so, then it would be better to use a subproperty of `obeu-dimension:functionalClassification`. As we will describe in [D1.5](https://docs.google.com/document/d/1wBA6-4krWuzD2N2RXHddGcIfNFOuLDXKiMIDCKnZRQU/edit#), if a specific code list is defined, then a subproperty of the core dimensions should be used.

**Comment by jindrichmynarz** [comment]
Looking at the DSD, this seems to be the issue for most reused core classification components of the OpenBudgets.eu data model. Just define local subproperties for the components using a custom code list.

**Comment by skarampatakis** [comment]
OK, we will wait for the submitted version of D1.5 to make the required changes.

**Comment by jindrichmynarz** [comment]
D1.5 is due in September 2016, so this is probably better addressed now.

**Comment by skarampatakis** [comment]
If I understand correct, there should be a different approach about both DSDs and datasets in order to conform with this issue. For example, let's take a slice from Municipality of Thessaloniki budget.

Now : 

```
thess-be2015-slice:1 a qb:Slice ;
    obeu-dimension:administrativeClassification <http://data.openbudgets.eu/resource/codelist/kae-ota-administration-2014/40> ;
    obeu-dimension:economicClassification <http://data.openbudgets.eu/resource/codelist/kae-ota-exodwn-2014/6011> ;
    qb:sliceStructure <http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2015/slice/slice-by-functionalCode> ;
    obeu-dimension:functionalClassification <http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2015/codelist/40/6011.01.01> ;
    qb:observation thess-be2015-observation:1 , thess-be2015-observation:2 , thess-be2015-observation:3 , thess-be2015-observation:4 , thess-be2015-observation:5 .
```

For this slice there are defined three different dimensions. Each one uses a specific codelist. For every dataset in Greek Municipalities this is the status of codelists:

`obeu-dimension:functionalClassification` there are specific codelists for every year and municipality. 
`obeu-dimension:administrativeClassification` specific for every municipality but the same across the years.
`obeu-dimensiion:economicClassification` all datasets use the same codelist. 

so to sum up.

In order to conform with the Data Model we have to:
1) use diferrent DSD for every dataset as the components will not be the same. 
2) use different dimensions for `functionalClassification` as subproperties of obeu-dimension:functionalClassification
3) use different dimension for `administrativeClassification` for every municipality. 
4) use the same dimension for `economicClassification` for every dataset but as a subproperty of `obeu-dimension:economicClassification`.

So the above example would transform into this:

```
thess-be2015-slice:1 a qb:Slice ;
    thess-dimension:administrativeClassification <http://data.openbudgets.eu/resource/codelist/kae-ota-administration-2014/40> ;
    gr-dimension:economicClassification <http://data.openbudgets.eu/resource/codelist/kae-ota-exodwn-2014/6011> ;
    qb:sliceStructure <http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2015/slice/slice-by-functionalCode> ;
    thess-be2015-dimension:functionalClassification <http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2015/codelist/40/6011.01.01> ;
    qb:observation thess-be2015-observation:1 , thess-be2015-observation:2 , thess-be2015-observation:3 , thess-be2015-observation:4 , thess-be2015-observation:5 .


#----dimension definition
thess-dimension:administrativeClassification a rdf:Property, qb:CodedProperty, qb:DimensionProperty ;
    rdfs:label "Administration offices of Municipalty of Thessaloniki"@en ;
    rdfs:comment "Codelist for administration offices for the Municpalty of Thessaloniki"@en ;
    rdfs:subPropertyOf obeu-dimension:administrativeClassification ;
    qb:codeList thess-codelist:thess-administrations ;
    rdfs:isDefinedBy <http://example.openbudgets.eu/ontology/dsd/thess-budget-2015> . 
```

Are these correct in order to proceed with justifications?

**Comment by jindrichmynarz** [comment]
The practice is: If you define a custom code list (via `qb:codeList`), then you should create a subproperty of a core component property.

If I read your example correctly (some of it may have been lost in formatting, you may try triple back-ticks to delimit code blocks), I think they are in line with the mentioned practice.

**Comment by skarampatakis** [comment]
Changes have been made for [Municipality of Thessaloniki 2011 expenditure budget](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-thessaloniki/dataset/budget-thessaloniki-expenditure-2011.ttl). Please check if everything is in place as it is supposed to.

**Comment by jindrichmynarz** [comment]
The Turtle syntax of `datasets/greek-municipalities/municipality-of-thessaloniki/dsd/thess-be2011-dsd.ttl` is invalid (dots instead of semicolons, missing prefix definitions). Please correct it.

**Comment by skarampatakis** [comment]
Corrections done.

**Comment by jindrichmynarz** [comment]
`thess-be2011-dsd-slice:slice-by-functionalCode` should be associated with a `qb:DataStructureDefinition` via `qb:sliceKey`. Every define dimension should declare `rdfs:range` (see this [integrity constraint](https://www.w3.org/TR/vocab-data-cube/#ic-4)).

**Comment by skarampatakis** [comment]
`rdfs:range skos:Concept` have been included for every dimension and corrected `qb:sliceKey` association.

**Comment by jindrichmynarz** [comment]
Thanks. The DSD looks fine now.

**Comment by skarampatakis** [comment]
OK. The rest of the datasets will be updated as soon as possible to reflect these changes. If there are any other problems please inform.

**Comment by HimmelStein** [comment]
Hi, 
in which .ttl files are obeu-dimension:budgetaryUnit  obeu-attribute:currency,  obeu-attribute:currency defined? I could not find them at https://github.com/openbudgets/data-model.git?

**Comment by skarampatakis** [comment]
It is on
https://github.com/openbudgets/data-model/blob/master/budget/budget-components.ttl

**Comment by HimmelStein** [comment]
yes, thanks.
