### ISSUE TITLE
esif-codelist:functions is missing

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#44]
`<http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/functions>` code list declared in [ESIF's DSD](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl#L65) is missing. Is it available somewhere?

**Comment by fathoni** [comment]
It was a typo and should be `<http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/function>` instead. The codelist is avilable [here](http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/functions) .

**Comment by jindrichmynarz** [comment]
The [ESIF dataset](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dataset/ESIF-2014-2020.ttl) contains a copy of its DSD with the invalid reference to `esif-codelist:functions`. It would probably be best to remove the DSD from the dataset to ease maintenance and maintain it separately in [here](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl).

**Comment by fathoni** [comment]
I'm a bit concerned with validation if the DSD is excluded. Alternatively, it is still included but using the updated DSD and pipeline. Anyway, the transformed dataset will be updated using the latest development of the codelist.

**Comment by jindrichmynarz** [comment]
The validation would work out fine even with the DSD included. The problem was that the included DSD was incorrect (out-of-date), so I proposed not to duplicate it to make fixes easier.
