### ISSUE TITLE
ESIF missing some dimensions attached to qb:DataSet

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#46]
The [ESIF dataset](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dataset/ESIF-2014-2020.ttl) is missing some dimensions attached to `qb:DataSet` (i.e., having `qb:componentAttachment qb:DataSet` in the [dataset's DSD](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl)). The missing dimensions are [`obeu-dimension:budgetPhase`](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl#L31-L32) and [`obeu-dimension:fiscalPeriod`](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl#L35-L36).

**Comment by fathoni** [comment]
I am unsure about the way I defined the interval, please check on the last three lines in the transformed [dataset](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dataset/ESIF-2014-2020.ttl). Is it correct?

**Comment by jindrichmynarz** [comment]
The representation of the fiscal period looks fine to me. Is there any reason why have you used `interval:IrregularInterval` instead of the vanilla `time:Interval`?

**Comment by fathoni** [comment]
I thought `time:Interval` was (implicitly) reserved for denominated interval. I'll update this into `time:Interval` if that's not the case.

**Comment by jindrichmynarz** [comment]
What do you mean by "denominated interval"?

`interval:IrregularInterval` is a subclass of `time:Interval`, so each of its instances can be automatically inferred to be an instance of `time:Interval` too, but this adds another processing step. However, if there is value in distinguishing `interval:IrregularInterval`, then we can use it.

**Comment by fathoni** [comment]
I was thinking to differentiate denominated interval like the interval of one "Week", one "Month", one "Year" and so on. I'll revert back to Interval instead.

**Comment by jindrichmynarz** [comment]
So you mean "denominated" as in "specific"? There's nothing wrong with using specific subclasses of `time:Interval`.

However, I'm not sure if I understand the description of `interval:IrregularInterval`: _"A business interval outside of the normal pattern of business intervals. In the UK companies house allow an annual reporting interval to be extended by upto 6 months once in 5 years (and at other exceptional times)."_

**Comment by fathoni** [comment]
Yes, I meant specific time interval. This "exceptional times" phrase sounds ambiguous for me. The dataset is currently using `Interval` instead. Let me know if it is necessary to use `IrregularInterval`.

**Comment by jindrichmynarz** [comment]
I think using `time:Interval` is a good choice here, since the meaning of `interval:IrregularInterval` is unclear to both of us.
