### ISSUE TITLE
Define custom components in the Greek municipalities DSD

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#5]
Custom components in the [Greek municipalities DSD](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/dsd/dsd.ttl), such as `gr-dimension:budgetPhase`, should be defined and described in RDF.

**Comment by skarampatakis** [comment]
it is described in here [datasets/greek-municipalities/codelist/budget-phase.ttl](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/codelist/budget-phase.ttl)

**Comment by jindrichmynarz** [comment]
Ah, OK. Though I think bundling the property with the DSD is more natural than bundling it with the code list.

**Comment by skarampatakis** [comment]
This is a problem in this phase as we have only RDF files. If these are over a triple store, that is not an issue.

**Comment by jindrichmynarz** [comment]
Yes, exactly.
