### ISSUE TITLE
ESIF dataset refers to non-existent esif-codelist:MS

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#53]
While the [ESIF's DSD](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dsd/ESIF-2014-2020.ttl) defines `<http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/memberStates>` as the code list of `esif-dimension:memberStates`, the [ESIF data](https://github.com/openbudgets/datasets/blob/master/ESIF/2014/dataset/ESIF-2014-2020.ttl) defines the code list to be `<http://data.openbudgets.eu/resource/ESIF-2014-2020/codelist/MS>`, which doesn't exist. This is caused by the duplication of the DSD in the dataset, which makes its maintenance more difficult and error-prone, as discussed [here](https://github.com/openbudgets/datasets/issues/44#issuecomment-225301953).

**Comment by fathoni** [comment]
DSD is now no longer included in the transformed dataset,  and the dataset and the pipeline has been updated.
