### ISSUE TITLE
Missing namespace prefix in Rethymno revenue DSD

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#56]
The [DSD of the revenue of Rethymno](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-rethymno/dsd/rethymno-r2016-dsd.ttl) is missing the namespace for the prefix `rethymno-br2016-dimension`, which makes the file syntactically invalid. Please define the namespace for this prefix via `@prefix`.

**Comment by NotisPhil** [comment]
Actually, it was rather a typo (prefix rethymno-r2016-dimension is used).

**Comment by jindrichmynarz** [comment]
OK, I see this is now fixed.
