### ISSUE TITLE
Heraklion revenue budget 2014 contains an invalid amount

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#60]
[Heraklion revenue budget 2014](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/dataset/heraklion-budget-revenue-2014.ttl) contains an invalid amount `obeu-measure:amount "(ΚΑ 20-7341001)"^^xsd:decimal`.

**Comment by NotisPhil** [comment]
The label of the slice in the dataset containing the ';' character that separated the csv columns, caused that error. Fixed.
