### ISSUE TITLE
Kalamaria expenditure budget 2004 contains invalid amounts

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#61]
[Kalamaria expenditure budget 2004](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-kalamaria/dataset/kalamaria-budget-expenditure-2004.ttl) contains invalid amounts, such as `obeu-measure:amount "Σύναψη προγραμματικής σύμβασης με την ΔΕΠΟΣ ΑΕ για την εκπόνηση μελετών των έργων του επιχειρησιακού σχεδίου του Δήμου.Αναζωογόνηση της περιοχής εργατικών κατοικιών Φοίνικα στην Καλαμαριά"^^xsd:decimal`.

**Comment by NotisPhil** [comment]
fixed 13 wrong slices.
