### ISSUE TITLE
Kalamaria expenditure budget 2005 contains invalid amount "Α-05)"

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#62]
[Kalamaria expenditure budget 2005](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-kalamaria/dataset/kalamaria-budget-expenditure-2005.ttl) contains invalid amount `Α-05)` typed as `xsd:decimal`.

**Comment by NotisPhil** [comment]
A column-separating character in the label of the slice caused this error. Fixed the amounts of the observations of that slice (35.7322.40).
