### ISSUE TITLE
Katerini expenditure budgets 2011-2016 contain invalid IRIs with backticks

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#63]
Katerini expenditure budgets 2011-2016 contain invalid IRIs with backticks; e.g., `<http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2011/codelist/25/7336.844`>` in the [2011 budget](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-katerini/dataset/katerini-budget-expenditure-2011.ttl).

**Comment by NotisPhil** [comment]
fixed.
