### ISSUE TITLE
Naousa expenditure budgets 2011-2016 contain invalid amounts

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#64]
Naousa expenditure budgets 2011-2016, such as the [2011 budget](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-naousa/dataset/naousa-budget-expenditure-2011.ttl), contain invalid amounts `obeu-measure:amount "και ανάδειξης του ορεινού οικισμού Αρκοχωρίου - ΙΔΙΑ ΕΣΟΔΑ"^^xsd:decimal`.

**Comment by NotisPhil** [comment]
fixed.
