### ISSUE TITLE
Epirus expenditure code lists 2012 and 2013 and revenue code lists 2015 and 2016 contain spaces in IRIs

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#66]
[Epirus expenditure code lists 2012 and 2013 and revenue code lists 2015 and 2016](https://github.com/openbudgets/datasets/tree/master/greek-municipalities/region-of-epirus/codelist) contain spaces in IRIs, which makes them invalid. For example:

``` turtle
skos:narrower <http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2013/codelist/04/071/9483 (α)> , <http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2013/codelist/04/071/9483 (β) ;
```

These invalid IRIs are also used in the Epirus datasets for 2012, 2013, 2015, and 2016.

**Comment by NotisPhil** [comment]
Fixed the expenditure datasets/codelists. Couldn't find the case in revenue code lists. Can you provide some more info?

**Comment by jindrichmynarz** [comment]
You can find invalid IRIs in RDF data using an RDF parser, such as [Apache Jena's Riot](https://jena.apache.org/documentation/io/).

``` bash
riot --validate epirus-budget-revenue-codelist-2015.ttl
10:01:07 ERROR riot                 :: [line: 3898, col: 110] Bad character in IRI (space): <http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2015/codelist/01/071/Τ.110[space]...>
```

This indicates an invalid IRI on line 3898. Similarly, you can test the 2016 revenue code list:

``` bash
riot --validate epirus-budget-revenue-codelist-2016.ttl
10:02:58 ERROR riot                 :: [line: 4260, col: 110] Bad character in IRI (space): <http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2016/codelist/01/071/Τ.110[space]...>
```

**Comment by NotisPhil** [comment]
Fixed them too.
