### ISSUE TITLE
Trailing slash in Rethymno expenditure code list 2016

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#67]
Some concepts in the [Rethymno expenditure code list 2016](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-rethymno/codelist/rethymno-budget-expenditure-codelist-2016.ttl) link by `skos:inScheme` to `<http://data.openbudgets.eu/resource/dataset/budget-rethymno-expenditure-2016/codelist/>`, while other links to `<http://data.openbudgets.eu/resource/dataset/budget-rethymno-expenditure-2016/codelist>`. The concept scheme for this code list is identified as `<http://data.openbudgets.eu/resource/dataset/budget-rethymno-expenditure-2016/codelist>`, so the trailing slash from the other IRI variant should be removed.

**Comment by jindrichmynarz** [comment]
The same problem also appears in these code lists:
- [Karpenisi, 2016, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-expenditure-codelist-2016.ttl)
- [Karpenisi, 2015, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-expenditure-codelist-2015.ttl)
- [Karpenisi, 2014, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-expenditure-codelist-2014.ttl)
- [Karpenisi, 2016, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-revenue-codelist-2016.ttl)
- [Karpenisi, 2015, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-revenue-codelist-2015.ttl)
- [Karpenisi, 2014, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-karpenisi/codelist/karpenisi-budget-revenue-codelist-2014.ttl)
- [Heraklion, 2015, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2015.ttl)
- [Heraklion, 2014, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2014.ttl)
- [Heraklion, 2013, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2013.ttl)
- [Heraklion, 2012, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2012.ttl)
- [Heraklion, 2011, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2011.ttl)
- [Heraklion, 2010, revenue](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-revenue-codelist-2010.ttl)
- [Heraklion, 2015, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2015.ttl)
- [Heraklion, 2014, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2014.ttl)
- [Heraklion, 2013, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2013.ttl)
- [Heraklion, 2012, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2012.ttl)
- [Heraklion, 2011, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2011.ttl)
- [Heraklion, 2010, expenditure](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-heraklion/codelist/heraklion-budget-expenditure-codelist-2010.ttl)

**Comment by NotisPhil** [comment]
fixed 'em all.
