### ISSUE TITLE
Kalamaria expenditure budget 2005 invalid syntax

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#69]
[Kalamaria expenditure budget 2005](https://github.com/openbudgets/datasets/blob/master/greek-municipalities/municipality-of-kalamaria/dataset/kalamaria-budget-expenditure-2005.ttl) contains a superfluous quotation mark starting the value of `obeu-measure:amount`:

``` turtle
<http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2005/observation/35.7322.40/draft> a qb: Observation ;
  gr-dimension:budgetPhase obeu-budgetphase:draft ;
  obeu-measure:amount "30000.0 ;
  qb:dataSet <http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2005> .
```

**Comment by NotisPhil** [comment]
fixed.
