### ISSUE TITLE
ESIF & Aragon code lists contain intermediate data of the Tabular component

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#76]
ESIF & Aragon code lists contain intermediate data of the Tabular component. See [this search](https://github.com/openbudgets/datasets/search?l=turtle&q=%22http%3A%2F%2Flinked.opendata.cz%2Fontology%2Fodcs%2Ftabular%2Frow%22&utf8=%E2%9C%93). It possible, please map the intermediate Tabular data to SKOS.

**Comment by fathoni** [comment]
Hi Jindrich, could you please provide an example for  

> map the intermediate Tabular data to SKOS.

I am not quite clear what it means. Thank you!

**Comment by jindrichmynarz** [comment]
If there's some data output by the Tabular component that you haven't mapped, then you would use a SPARQL Update operation to transform it to SKOS. If there's just some superfluous output of the Tabular component, such as the `tabular:row` property, you could just add a SPARQL Update to delete it:

``` sparql
PREFIX tabular: <http://linked.opendata.cz/ontology/odcs/tabular/>

DELETE {
  ?s tabular:row ?o .
}
WHERE {
  ?s tabular:row ?o .
}
```

(Unfortunately, `DELETE WHERE {}` short-hand is not yet supported.)

**Comment by jindrichmynarz** [comment]
By the way, it seems you solved the unmapped Tabular output while resolving the other issues, so there are only extra `tabular:row`s.

**Comment by fathoni** [comment]
Bonn has been fixed, as a self note, ESIF will be fixed later.
