### ISSUE TITLE
Aragon code lists with skos:note instead of skos:notation

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#77]
Some Aragon code lists, such as [estructura_organica_aragon_2016](https://github.com/openbudgets/datasets/blob/master/Aragon/2016/codelist/estructura_organica_aragon_2016.ttl), contain `skos:note` instead of `skos:notation`. Is that intentional or a typo?

**Comment by fathoni** [comment]
The notation has been changed into unique code instead. Also, now an skos:note is used to indicate whether it is G / gastos (expenditure) or I / Ingresos (income) codelist.

**Comment by jindrichmynarz** [comment]
I think using `skos:note` to differentiate expenditure and income is superfluous because the Aragon code lists are already split by this difference.

**Comment by fathoni** [comment]
I will enlist the removal of `skos:note` as an enhancement task.
