### ISSUE TITLE
Modelling issues in the OpenCoesione sample

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/datasets#81]
Comments regarding the [main sample](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dataset/OCSample.ttl):
- `obeu-attribute:location` was deprecated in favour of [`obeu-optional:location`](https://github.com/openbudgets/data-model/blob/master/components.ttl#L264-L271) in the OpenBudgets.eu data model.
- `oc-dimension:programmeClassification` is in the [DSD](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dsd/OC-2007-2013-DSD.ttl), but is missing in the [sample](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dataset/OCSample.ttl). Is it needed (since the DSD also includes `oc-dimension:OCprogrammeClassification`)?
- Your `qb:SliceKey` (`oc-dsd-slice:slice-by-project`) also includes `obeu-attribute:location`, however, properties fixed in a slice key must be only dimensions (see [here](https://www.w3.org/TR/vocab-data-cube/#h3_slices)).
- The DSD defines the code list of `oc-dimension:QSNfunctionalClassification` to be `<http://data.openbudgets.eu/resource/codelist/qsn-functional-class>`, while the code list uses the IRI `<http://data.openbudgets.eu/resource/codelist/oc-qsn-functional-class>`.
- The DSD defines the code list of `oc-dimension:CUPeconomicClassification` to be `<http://data.openbudgets.eu/resource/codelist/cup-economic-class>`, while the code list uses the IRI `<http://data.openbudgets.eu/resource/codelist/oc-cup-economic-class>`.
- The DSD defines the code list of `oc-dimension:ATECOeconomicClassification` to be `<http://data.openbudgets.eu/resource/codelist/ateco-class>`, while the code list uses the IRI `<http://data.openbudgets.eu/resource/codelist/oc-ateco>`.
- The DSD defines the code list of `oc-dimension:CUPadministrativeClassification` to be `<http://data.openbudgets.eu/resource/codelist/cup-admin-class>`, while the code list uses the IRI `<http://data.openbudgets.eu/resource/codelist/oc-cup-admin-class>`.
- The code lists `<http://data.openbudgets.eu/resource/codelist/eu-functional-class>`, `<http://data.openbudgets.eu/resource/codelist/oc-programme-class-a>`, and `<http://data.openbudgets.eu/resource/codelist/oc-programme-class-b>` are missing.
- DCV validation reveals several violations of [IC-11](https://www.w3.org/TR/vocab-data-cube/#ic-11) for most dimensions, so you might check if they are actually dimensions and that data are available for all of them.

Comments regarding the [entities sample](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dataset/OCentities_sample.ttl):
- I think the `:legalStatus` property matches [rov:orgType](https://www.w3.org/TR/vocab-regorg/#ref_rov_orgType), so it can be either directly reused or used as a super-property.

Comments regarding the [projects sample](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dataset/OCprojects_sample.ttl):
- Project may have different statuses (`:projectStatus`) over time. Hence, I'd would attach `:projectStatus` directly as a property of `foaf:Project` instances, but instead create a data cube  with the dimensions of the project and date with a project status measure. This is similar to what I have done for the [ESF-CZ projects](https://github.com/openbudgets/datasets/blob/master/ESF-CZ/2007-2013/projects/dsd/project_statuses_dsd.ttl).
- I'd use `adms:identifier/skos:notation` instead of plain `skos:notation` as a way to represent project IDs.

**Comment by skarampatakis** [comment]
What is the status of this? Can we close it?

**Comment by jindrichmynarz** [comment]
I think we ended up not using OpenCoesione, so this issue is no longer relevant. Feel free to close it if you aim for a clear issue tracker.
