### ISSUE TITLE
Aggregation steps in OBEU Viewer 

### ISSUE THREAD

**Issue by fathoni** [openbudgets/datasets#85]
Bonn datasets come with a complex structure (with arbitraty dimensions and + / - values to indicate spending / revenue). @wk0206 and I experimented on the DCV-Valid dataset, however, there is a strange measure aggregated in the viewer. For example, this cost-center Bonn Budget available [here](http://apps.openbudgets.eu/viewer/bonn-budget-2022-costCenter__ceed0?measure=%22amount.sum%22&groups%5B%5D=%22businessArea.notation%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en). @larjohn , what kind of queries are made to display such tree map? We will try adapting the query to remodel the datasets, so that the visualization display the correct amount.

**Comment by larjohn** [comment]
Have you already changed the model? Because I was working on it and suddenly the API does not return data.

**Comment by fathoni** [comment]
Yes, we've changed the model of the dataset to see if remodeling would fix the measure value problem.
I did not know that you were working with the previous dataset, but I have asked @liyakun to reimport the previous Bonn data into virtuoso.

**Comment by larjohn** [comment]
What is exactly strange in this visualization? The existence of some property? The sum of values? What is the expected behavior?

**Comment by fathoni** [comment]
It is strange in the sense that the sum of values on the visualization is very big, for example, this particular dataset:
http://apps.openbudgets.eu/viewer/bonn-budget-2022-costCenter__ceed0?measure=%22amount.sum%22&groups%5B%5D=%22businessArea.notation%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en 

![image](https://user-images.githubusercontent.com/1597027/28386758-db7b9c4e-6ccc-11e7-9916-be150d1814fc.png)

I expect that the value of visualization should be less than a billion EUR. I was wondering if this is a data modeling issue.

**Comment by larjohn** [comment]
We don't even see the same picture. While in the viewer, can you open your dev tools and send me the headers from the aggregate request
http://apps.openbudgets.eu/api/3/cubes/bonn-budget-2022-costCenter__ceed0/aggregate?drilldown=businessArea.notation%7CbusinessArea.prefLabel&order=amount.sum:desc&pagesize=30

Please don't open it in a separate tab and dont do ctrl+f5, so that we can examine if it is just the well known cache issue

**Comment by fathoni** [comment]
Here it is: 

```
Request URL:http://apps.openbudgets.eu/api/3/cubes/bonn-budget-2022-costCenter__ceed0/aggregate?drilldown=businessArea.notation%7CbusinessArea.prefLabel&order=amount.sum:desc&pagesize=30
Request Method:GET
Status Code:200 OK (from disk cache)
Remote Address:193.175.162.98:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
Cache-Control:max-age=7776000
Content-Type:application/json
Date:Thu, 20 Jul 2017 07:58:29 GMT
Expires:Wed, 18 Oct 2017 07:58:29 GMT
Server:nginx/1.10.2
X-Powered-By:PHP/7.0.7
Request Headers
Provisional headers are shown
Referer:http://apps.openbudgets.eu/viewer/bonn-budget-2022-costCenter__ceed0?measure=%22amount.sum%22&groups%5B%5D=%22businessArea.notation%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Query String Parameters
view source
view URL encoded
drilldown:businessArea.notation|businessArea.prefLabel
order:amount.sum:desc
pagesize:30

```

**Comment by larjohn** [comment]
I have fixed a possible issue in the queries that might be the reason behind inconsistent and/or random responses. 

What I can't fix is Firefox caching a file for ever, even after CTRL+F5

Here is something that helps:

https://support.mozilla.org/en-US/questions/1103414#answer-828423

**Comment by fathoni** [comment]
Thank you, I have checked the viewer in both Chrome and Firefox and seems that it is okay for Bonn split data sets. The visualizations are now consistent in both Browsers (except on PSP element split which _sometimes_ renders empty tree map on Business Area dimension on Chrome, but it the least concern for now and can be visualized properly if I open incognito mode).
