### ISSUE TITLE
Bonn dataset codelist concepts missing inScheme property

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/datasets#88]
Some concepts of the the Bonn dataset codelists have a missing skos:inScheme property

eg

http://data.openbudgets.eu/resource/codelist/kostenartenuebersicht_bonn/K11-010

**Comment by skarampatakis** [comment]
Any update on this?

**Comment by fathoni** [comment]
hi Sotiris, not yet, I will update this issue once it is done, thanks!

**Comment by fathoni** [comment]
The dump and pipeline have been updated, but the graph has not been updated yet. I have notified @hantongliu to update the graph as he has the authority to do so.

**Comment by fathoni** [comment]
Looks like the graph has been updated. Could you verify if this has been fixed, @skarampatakis?

**Comment by skarampatakis** [comment]
Just checked and seems to be fixed. Thanks!
